---
entrypoint: service.p6
cro: 1
env:
  - name: REALWORLD_DSN
    value: host=localhost port=5432 user=raku password=raku dbname=realworld sslmode=disable  
endpoints: 
  - 
    port-env: REALWORLD_API_PORT
    name: HTTP
    id: http
    protocol: http
    host-env: REALWORLD_API_HOST
id: raku-cro-realworld-example-api-app
links:  []
name: raku-cro-realworld-example-api-app
ignore:
  - foo
